# Generated by Django 4.1.4 on 2023-04-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.temporada'),
        ),
    ]
