# Generated by Django 4.1.4 on 2023-04-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_receta_alter_ingrediente_nombre_ingredientereceta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientereceta',
            old_name='idReceta',
            new_name='nombre',
        ),
    ]
